# Vendor stubs for the Northstar lab.
# Mappings are copied into the image so bind mounts are not required at runtime.
FROM wiremock/wiremock:3.10.0

COPY mappings /home/wiremock/mappings
COPY __files /home/wiremock/__files
